apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: game2048
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-stagging"
spec:
  tls:
  - hosts:
      - host.domain.ext
    secretName: echo-tls
  rules:
  - http:
      paths:
      - backend:
          serviceName: "deployment-2048"
          servicePort: 80